$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1442386616368.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d131929b114942569c3beed06220ddde",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"312241cfc066498bac4e8e03ffbcaf2f",
          "label":"img01",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":10},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /newportal/contactslist.jsp",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/newportal/contactslist.jsp",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"5579d7edcfe64314a11abc1bbab8a716",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4b7264694679483bafa91c0cce9a1ffd",
                  "label":"",
                  "parentDynamicPanel":"312241cfc066498bac4e8e03ffbcaf2f",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"50ec3b0b4a3b42dd90e6687ef0ab8590",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"312241cfc066498bac4e8e03ffbcaf2f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 img01 到 状态2",
                              "panelsToStates":[{
                                  "panelPath":["312241cfc066498bac4e8e03ffbcaf2f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"a552fe56f3f64924aa3a5426acc458ca",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"90cab05c3fe8470c977b5aa39702e323",
                  "label":"",
                  "parentDynamicPanel":"312241cfc066498bac4e8e03ffbcaf2f",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "opacity":"0.5",
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8b56315044e541bd8f7559d5a98f1d50",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"312241cfc066498bac4e8e03ffbcaf2f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.5",
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 img01 到 状态1",
                              "panelsToStates":[{
                                  "panelPath":["312241cfc066498bac4e8e03ffbcaf2f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"c9aaba8b3cd7417ea2092d53bd12cd36",
          "label":"img02",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":10},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /sms/SmsMessageEditTab.jsp",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/sms/SmsMessageEditTab.jsp",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"9e1bca962905409a8178cad43d9fd8a5",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9d1e3896ef3746f0a57e394b364ffd9c",
                  "label":"",
                  "parentDynamicPanel":"c9aaba8b3cd7417ea2092d53bd12cd36",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ee9b3dd076024906bf6e93040c98675e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c9aaba8b3cd7417ea2092d53bd12cd36",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 img02 到 状态2",
                              "panelsToStates":[{
                                  "panelPath":["c9aaba8b3cd7417ea2092d53bd12cd36"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u6.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"4f0095ab7c454ec7a651cef6836f9eca",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"67811a165dc74559af8e9fbe064c5ed2",
                  "label":"",
                  "parentDynamicPanel":"c9aaba8b3cd7417ea2092d53bd12cd36",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "opacity":"0.5",
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a15d39f48d9b409383b4a2d0639e6db5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c9aaba8b3cd7417ea2092d53bd12cd36",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.5",
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 img02 到 状态1",
                              "panelsToStates":[{
                                  "panelPath":["c9aaba8b3cd7417ea2092d53bd12cd36"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u6.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"774abc3405764c0192a387b4465ff9fc",
          "label":"img03",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":10},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /meeting/data/MeetingCalView.jsp",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/meeting/data/MeetingCalView.jsp",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ef10ae5d8461416493fd757f6adbe8ba",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6ec1019be1c44a418c46bc10605d75b6",
                  "label":"",
                  "parentDynamicPanel":"774abc3405764c0192a387b4465ff9fc",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7cd59b3938454795bb9c9414c915f23a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"774abc3405764c0192a387b4465ff9fc",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 img03 到 状态2",
                              "panelsToStates":[{
                                  "panelPath":["774abc3405764c0192a387b4465ff9fc"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u11.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"a381e4f0d39c4458ae105b54b9e05ed1",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9e704d11d4aa402792f8a31aa3717927",
                  "label":"",
                  "parentDynamicPanel":"774abc3405764c0192a387b4465ff9fc",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "opacity":"0.5",
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"38f36d8e05514643868e0219d760abb4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"774abc3405764c0192a387b4465ff9fc",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.5",
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 img03 到 状态1",
                              "panelsToStates":[{
                                  "panelPath":["774abc3405764c0192a387b4465ff9fc"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u11.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"1bb4536fcc344df2b7e6ae08a8f3eaeb",
          "label":"img04",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":100},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /favourite/ManageFavourite.jsp",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/favourite/ManageFavourite.jsp",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"37ab4005a5644f4a9e87626258915ddb",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6d31e38f1e2b4728896986cf36b16715",
                  "label":"",
                  "parentDynamicPanel":"1bb4536fcc344df2b7e6ae08a8f3eaeb",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b3098af6fb904aff8d390b0b5b07ef8d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1bb4536fcc344df2b7e6ae08a8f3eaeb",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 img04 到 状态2",
                              "panelsToStates":[{
                                  "panelPath":["1bb4536fcc344df2b7e6ae08a8f3eaeb"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u16.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"dbcd8ddfa9e7435db160d4b561ad56af",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6f03ded537404bde9a83ebfade129204",
                  "label":"",
                  "parentDynamicPanel":"1bb4536fcc344df2b7e6ae08a8f3eaeb",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "opacity":"0.5",
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8c82aaaf72344c1a8f9874ecdc88d669",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1bb4536fcc344df2b7e6ae08a8f3eaeb",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.5",
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 img04 到 状态1",
                              "panelsToStates":[{
                                  "panelPath":["1bb4536fcc344df2b7e6ae08a8f3eaeb"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u16.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"a8a20af1306743dd81c808bf83a1c47f",
          "label":"img05",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":100},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /blog/myBlog.jsp",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/blog/myBlog.jsp",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"4c077c22a53142e992a3625c6a84a7cf",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d780aad35e0e41bebe02b344f166b79a",
                  "label":"",
                  "parentDynamicPanel":"a8a20af1306743dd81c808bf83a1c47f",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"94fbd1fa613a4cbea7ec409afac4ad85",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a8a20af1306743dd81c808bf83a1c47f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 img05 到 状态2",
                              "panelsToStates":[{
                                  "panelPath":["a8a20af1306743dd81c808bf83a1c47f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u21.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"34ee265f877c43e2a9eed457378a2f77",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"802621efb9b6449689d11ba77fca212c",
                  "label":"",
                  "parentDynamicPanel":"a8a20af1306743dd81c808bf83a1c47f",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "opacity":"0.5",
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0c1ce3c7ac94dacbbb910f2a81719bd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a8a20af1306743dd81c808bf83a1c47f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.5",
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 img05 到 状态1",
                              "panelsToStates":[{
                                  "panelPath":["a8a20af1306743dd81c808bf83a1c47f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u21.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"915ddaa6a8f04c3b9d5fa9d41f7e5cd4",
          "label":"img06",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":101},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /workplan/data/WorkPlan.jsp",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/workplan/data/WorkPlan.jsp",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"7e1abd891a0b4188b5b87dec9472762b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b35d843deba44dfc92359492db70e86e",
                  "label":"",
                  "parentDynamicPanel":"915ddaa6a8f04c3b9d5fa9d41f7e5cd4",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f41bf16064b04feaab1d819b176abfbf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"915ddaa6a8f04c3b9d5fa9d41f7e5cd4",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 img06 到 状态2",
                              "panelsToStates":[{
                                  "panelPath":["915ddaa6a8f04c3b9d5fa9d41f7e5cd4"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u26.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"0b9b7c246bde4ac5820fa3fef597f3f7",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ed0d82bd470f49beb2e3fefb7987d7ae",
                  "label":"",
                  "parentDynamicPanel":"915ddaa6a8f04c3b9d5fa9d41f7e5cd4",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "opacity":"0.5",
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"db4875bac7a04f4babd774a3b7ea473a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"915ddaa6a8f04c3b9d5fa9d41f7e5cd4",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.5",
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 img06 到 状态1",
                              "panelsToStates":[{
                                  "panelPath":["915ddaa6a8f04c3b9d5fa9d41f7e5cd4"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u26.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "312241cfc066498bac4e8e03ffbcaf2f":{
      "scriptId":"u0"},
    "4b7264694679483bafa91c0cce9a1ffd":{
      "scriptId":"u1"},
    "50ec3b0b4a3b42dd90e6687ef0ab8590":{
      "scriptId":"u2"},
    "90cab05c3fe8470c977b5aa39702e323":{
      "scriptId":"u3"},
    "8b56315044e541bd8f7559d5a98f1d50":{
      "scriptId":"u4"},
    "c9aaba8b3cd7417ea2092d53bd12cd36":{
      "scriptId":"u5"},
    "9d1e3896ef3746f0a57e394b364ffd9c":{
      "scriptId":"u6"},
    "ee9b3dd076024906bf6e93040c98675e":{
      "scriptId":"u7"},
    "67811a165dc74559af8e9fbe064c5ed2":{
      "scriptId":"u8"},
    "a15d39f48d9b409383b4a2d0639e6db5":{
      "scriptId":"u9"},
    "774abc3405764c0192a387b4465ff9fc":{
      "scriptId":"u10"},
    "6ec1019be1c44a418c46bc10605d75b6":{
      "scriptId":"u11"},
    "7cd59b3938454795bb9c9414c915f23a":{
      "scriptId":"u12"},
    "9e704d11d4aa402792f8a31aa3717927":{
      "scriptId":"u13"},
    "38f36d8e05514643868e0219d760abb4":{
      "scriptId":"u14"},
    "1bb4536fcc344df2b7e6ae08a8f3eaeb":{
      "scriptId":"u15"},
    "6d31e38f1e2b4728896986cf36b16715":{
      "scriptId":"u16"},
    "b3098af6fb904aff8d390b0b5b07ef8d":{
      "scriptId":"u17"},
    "6f03ded537404bde9a83ebfade129204":{
      "scriptId":"u18"},
    "8c82aaaf72344c1a8f9874ecdc88d669":{
      "scriptId":"u19"},
    "a8a20af1306743dd81c808bf83a1c47f":{
      "scriptId":"u20"},
    "d780aad35e0e41bebe02b344f166b79a":{
      "scriptId":"u21"},
    "94fbd1fa613a4cbea7ec409afac4ad85":{
      "scriptId":"u22"},
    "802621efb9b6449689d11ba77fca212c":{
      "scriptId":"u23"},
    "e0c1ce3c7ac94dacbbb910f2a81719bd":{
      "scriptId":"u24"},
    "915ddaa6a8f04c3b9d5fa9d41f7e5cd4":{
      "scriptId":"u25"},
    "b35d843deba44dfc92359492db70e86e":{
      "scriptId":"u26"},
    "f41bf16064b04feaab1d819b176abfbf":{
      "scriptId":"u27"},
    "ed0d82bd470f49beb2e3fefb7987d7ae":{
      "scriptId":"u28"},
    "db4875bac7a04f4babd774a3b7ea473a":{
      "scriptId":"u29"}}});